### ISSUE TITLE
【网站公告】园子被处罚，请大家不要发布/转载任何网络小说

### ISSUE THREAD

**Issue by cnblogs-team** [cnblogs/announcements#1]
昨天收到了处罚决定书，15天内缴罚款，这对困难中的园子又是一次雪上加霜。

被处罚是因为8年之前用户转载的4篇网络小说包含危害社会公德的内容，其中1篇发布时间是2010年，1篇发布时间是2013年，2篇发布时间是2015年。

2021年，为了网站的合规运营，我们用了大半年时间对历史博文进行重新审核，但这4篇违规博文机审+人工审核都没发现。

这次处罚让我们进一步认识到网站合规运营重于泰山，我们会吸取教训，进一步加强审核工作。

园子是一个技术社区，没有办理《网络出版服务许可证》，不能发布网络小说，请大家不要发布/转载任何网络小说。

我们会一边加强审核工作，一边努力找到园子的商业化出路，想尽一切办法让园子活下去。

如果找到商业化出路，园子将投入做一件一直梦寐以求的事情——做面向全球开发者的海外站。

**Comment by kindear** [comment]
真离谱，不会是csdn 举报的把，哈哈哈哈

**Comment by cnblogs-team** [comment]
@kindear 您好，这次处罚不是因为举报。

**Comment by sevencat** [comment]
是人工智能ai分析出来的吗？果然高科技。

**Comment by tonyqus** [comment]
也不是第一次了，上一次是2021年的事
![ba0a94fe2d881dd9f78e6ef46d193d3](https://github.com/cnblogs/announcements/assets/772561/f582d677-efb9-4526-ae2f-3f24c7bbbac9)

**Comment by tonyqus** [comment]
我想了解下，按现在的现金流，博客园能撑到今年年底吗？

**Comment by lousaing** [comment]
要不把小说转成gbk 让看的人自己转

**Comment by cnblogs-team** [comment]
@tonyqus 您好，要看今年的商业化努力的进展

**Comment by thanksqq** [comment]
天涯等一系列论坛被关被关，博客园被关是迟早的事，赶紧把论坛帖子打包备份，随时做好关站的准备；同时在海外申请域名和网站，文章同步发布，就这点访问量，2C4G的VPS绰绰有余了。

**Comment by teacoding** [comment]
吐槽真理部那帮家伙。

**Comment by tonyqus** [comment]
吐槽有什么用，有本事去街上举白纸呀

**Comment by xupeihuagudulei** [comment]
过来支持下！话说那个账号是不是永久封禁了。

**Comment by seamusic** [comment]
真是离了大谱！

**Comment by Wolffy101** [comment]
这样怎么发展gpt 。都没有内容学习了

**Comment by lihong1232** [comment]
这真是无语了，，，，，陈芝麻烂谷子都能被翻出来，看来真是这片土地容不下技术的心。
无心之过，虽过不罚。不知道说什么了。

**Comment by yisibugua** [comment]
![60](https://github.com/cnblogs/announcements/assets/7897207/d99b18b4-d330-4f62-a042-ba71331a7aac)
离谱

**Comment by MengYuanHan** [comment]
希望博客园能一直做下去啊？怎么突然间就这样了？

**Comment by sunday123** [comment]
`没有办理《网络出版服务许可证》，不能发布网络小说，请大家不要发布`

似曾相识

**Comment by sevencat** [comment]
> `没有办理《网络出版服务许可证》，不能发布网络小说，请大家不要发布`
> 
> 似曾相识

也没有办理《代码出版服务许可证》吧，感觉迟早还是要被封。

**Comment by whitexiao** [comment]
估计得罪人了！！ 最高效的办法是先花钱去**咨询公司**摸清**门路**，然后准备钱务必按咨询公司的事先**约定好**的技巧上下打点，让**高人指导**安全经营，有实力的话最好是办理个10年期套餐。

**Comment by saltfishh** [comment]
博客园是技术类最后一篇净土了

**Comment by CSEwkm** [comment]
园子加油

**Comment by kamibababa** [comment]
加油

**Comment by shuizhugeju** [comment]
> 估计得罪人了！！ 最高效的办法是先花钱去**咨询公司**摸清**门路**，然后准备钱务必按咨询公司的事先**约定好**的技巧上下打点，让**高人指导**安全经营，有实力的话最好是办理个10年期套餐。

还能这样？

**Comment by seamusic** [comment]
> 估计得罪人了！！ 最高效的办法是先花钱去**咨询公司**摸清**门路**，然后准备钱务必按咨询公司的事先**约定好**的技巧上下打点，让**高人指导**安全经营，有实力的话最好是办理个10年期套餐。

要是有这钱，就不用整天想着怎么商业化了。感觉目前的博客园，服务器的费用都快支持不起了。

**Comment by tonyqus** [comment]
> > 估计得罪人了！！ 最高效的办法是先花钱去**咨询公司**摸清**门路**，然后准备钱务必按咨询公司的事先**约定好**的技巧上下打点，让**高人指导**安全经营，有实力的话最好是办理个10年期套餐。
> 
> 要是有这钱，就不用整天想着怎么商业化了。感觉目前的博客园，服务器的费用都快支持不起了。

所以我上次说，可能cnblogs年底就关了，就是感觉他们服务器费用都快付不出了。

**Comment by sevencat** [comment]
> > > 估计得罪人了！！ 最高效的办法是先花钱去**咨询公司**摸清**门路**，然后准备钱务必按咨询公司的事先**约定好**的技巧上下打点，让**高人指导**安全经营，有实力的话最好是办理个10年期套餐。
> > 
> > 
> > 要是有这钱，就不用整天想着怎么商业化了。感觉目前的博客园，服务器的费用都快支持不起了。
> 
> 所以我上次说，可能cnblogs年底就关了，就是感觉他们服务器费用都快付不出了。

有一说一吧，现在论坛这种知识型的大部分都是一些通用知识，还有好多其实没啥用的知识，感觉内容不是很专业，对大部分人来说也没啥用啊。也没有太多的量。

**Comment by tonyqus** [comment]
主要是国内技术论坛不行，国外挺好的，反正我已经不看国内技术网站7-8年了。

**Comment by qbmiller** [comment]
1. 网络这么多个人站长，有什么方法能吸引他们加入吗。
2. 不备案，然后公开api ,个人站长放自己喜欢东西，随时可导出走人。绑定个人域名，每年交服务器运营费。
再整点最近很火的rss /email订阅。 知识碎片整理? 那么多notion 笔记用户
3. 好知识，好文章到处都是，得搜集过来（引用就可以）
