### ISSUE TITLE
弹尽粮绝，会员救园：会员上线，命悬一线

### ISSUE THREAD

**Issue by cnblogs-team** [cnblogs/announcements#2]
自从今年4月[绝境求商](https://www.cnblogs.com/cmt/p/17280054.html)之后，园子苦苦支撑了4个月，能够支撑到现在，主要源于大家的[捐助](https://www.cnblogs.com/cmt/p/17320765.html)，一位园友的小额投资，以及天使投资方顺顺智慧的出手相救。感谢这段时间所有帮助过园子的朋友！

在当前极其困难的情况下，我们没有足够的力量在其他商业模式上搏一把，接下来园子走出困境的唯一希望，园子的命运就取决于——到年底有多少园友选择成为[VIP会员](https://cnblogs.vip/)。

园子生于偶然，长于天然，执于本然，困于漠然（商业化），难于突然（危机），接下来将交于自然——用户的自然选择。

不知道会有多少用户会选择帮助园子走出困境，但我们知道园子的存在与发展至今就是因为用户的选择。

不管结局如何，我们都无怨无悔，因为这是我们的选择，而且选择已经成为我们的使命。最无憾的人生之一就是找到自己的使命，并为之努力。

当2021年面临关站还是缴纳对园子来说巨额罚款的选择时，我们选择了坚持下去。

当2022年面临百度全面降权与收入暴降时，我们选择了坚持下去。

当2023年弹尽粮绝时，我们依然想选择坚持下去，但这一次如果没有足够多用户的支持，我们就没有足够的力量坚持下去。

会员上线，这是我们正式发布园子会员，之前放了一些链接，到目前已有[140位会员](https://home.cnblogs.com/vip)，感谢这些园友的支持！

命悬一线，这根从用户到会员的感情线，聚少成多将成为园子的命运线。

接下来，我们会保持心态：谋事在园，成事在用户。

接下来，我们会满怀期待：有园千里来相会，会员万维来救园。

接下来，我们会火力全开：全力以赴开发更多会员权益，让园子的会员成为非常超值的会员。

https://cnblogs.vip/

**Comment by xiaohuazi123** [comment]
支持！

**Comment by yikolemon** [comment]
支持

**Comment by hpclass** [comment]
已充值

**Comment by noah227** [comment]
加油

**Comment by FantansticYi** [comment]
加油

**Comment by xmskf** [comment]
支持!!!

**Comment by liupeng176** [comment]
支持，你们要想办法调整了

**Comment by TQG0021** [comment]
支持！
