### ISSUE TITLE
【故障公告】结束

### ISSUE THREAD

**Issue by cnblogs-team** [cnblogs/announcements#3]
结束

**Comment by DerickIT** [comment]
报警了吗

**Comment by Sorkai** [comment]
> 实在不行的话 能套cloudflare缓解吗

我觉得还真可以，就算慢点让正常用户先能看再说

**Comment by Dounutsubtly** [comment]
可以把攻击来源的段的流量切到ipv6上去，如果有四层防火墙的话，可以对MTU做一个判断，针对CC可以把登录查询各种接口放到验证码后面，或者需要proof of work需要计算一段时间才放行。

**Comment by zhupengfeivip** [comment]
不是用的阿里云吗，找阿里云帮忙啊？如果能阿里的安全产品可以解决，也可以尝试一下啊，一直不能访问也不是个事吧

**Comment by ouyangguoyong** [comment]
看看这些请求里面的请求头和请求报文有哪些特征,正常用户请求和非法请求肯定是存在差异的,看看能不能从这些地方着手

**Comment by xiaohuazi123** [comment]
经常故障，最近
